version: '2'
services: 
  databases:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSLQ_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATBASE=test
  web:
    image: jaydattmslc/discoveryserver:1.0
