server:
  port: 0

spring:
  application:
    name: employee-eureka-client
  
  datasource:
    url: jdbc:h2:file:~/test;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    


eureka:
  instance:
    instance-id: ${spring.application.name}:${random.int}

  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
      
      
#  client:
#    serviceUrl:      
#      defaultZone: https://cf-spring-eureka-server.cfapps.io/eureka