spring:
  profiles:
    active: profile-1

---
sample:
  property: This is profile one....
management:
  security:
    enabled: false
foo:
  value: 10
  
spring:
  datasource:
    url: jdbc:h2:file:~/test;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  profiles: profile-1

---
sample:
  property: This is profile two...
management:
  security:
    enabled: false
foo:
  value: 20
  
spring:
  datasource:
    url: jdbc:h2:file:~/test;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  profiles: profile-2
    